Repository Abhiramborige/react-app-mahabharath, pull requests merged in 2021-10, with the labels that each got.

#8 add missing relations for existing characters
  public/characters.json
  public/filter.json
Labels: hacktoberfest-accepted

#10 CSS to Sass. #9
  package-lock.json
  package.json
  src/Components/loader.jsx
  src/Components/navbar.jsx
  src/MainApp.js
  src/OtherPages/About.js
  src/OtherPages/Connect.js
  src/styles/extras.scss
  src/styles/index.css
  src/styles/index.scss
  src/styles/navbar.css
  src/styles/navbar.scss
Labels: hacktoberfest-accepted

#12 Add user authentication
  heroku.yml
  server/Dockerfile
  server/Dockerfile.dev
  server/README.md
  server/docker-compose.dev.yml
  server/index.js
  server/package-lock.json
  server/package.json
  server/scraper.js
  server/src/app.js
  server/src/controllers/AuthorizeUser.js
  server/src/controllers/CharacterInfo.js
  server/src/controllers/CreateKey.js
  server/src/controllers/CreateUser.js
  server/src/controllers/DeleteKey.js
  server/src/controllers/RefreshToken.js
  server/src/controllers/index.js
  server/src/entities/Key.js
  server/src/entities/User.js
  server/src/entities/index.js
  server/src/providers/index.js
  server/src/providers/wikipedia.js
  server/src/repositories/Key.js
  server/src/repositories/User.js
  server/src/repositories/index.js
  server/src/schemas/KeySchema.js
  server/src/schemas/UserSchema.js
  server/src/server.js
  server/src/use-cases/authorizeUser.js
  server/src/use-cases/characterInfo.js
  server/src/use-cases/createKey.js
  server/src/use-cases/createUser.js
  server/src/use-cases/deleteKey.js
  server/src/use-cases/index.js
  server/src/use-cases/refreshToken.js
  server/src/utils/emailHelper.js
  server/src/utils/expressCallback.js
  server/src/utils/jwtHelper.js
  server/src/utils/passwordHelper.js
  server/src/utils/uuidHelper.js
  server/wiki_api.js
  src/Components/online_info.jsx
Labels: hacktoberfest-accepted

#16 ✨add a sidebar
  src/Components/navbar.jsx
  src/styles/navbar.scss
Labels: hacktoberfest-accepted

#17 Added some characters
  package.json
  public/character_details.json
  public/characters.json
  public/filter.json
  server/package-lock.json
Labels: hacktoberfest-accepted

#20 Feat add more enhancement
  src/Components/navbar.jsx
  src/Components/themeChanger.jsx
  src/styles/navbar.scss
Labels: enhancement

#19 Client authentication
  Dockerfile.dev
  docker-compose.dev.yml
  package-lock.json
  package.json
  server/Procfile
  server/src/controllers/CreateUser.js
  server/src/entities/Key.js
  server/src/entities/User.js
  src/Components/online_info.jsx
  src/OtherPages/login.jsx
  src/providers/authentication.js
  src/providers/character.js
  src/providers/index.js
  src/providers/jwt.js
  src/providers/storage.js
Labels: documentation, enhancement, hacktoberfest-accepted
